spring:
  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  output.ansi.enabled: ALWAYS

# 디버그 모드 활성화
logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: DEBUG

app:
  jwt:
    secretKey: ${JWT_SECRET}
    header:
      name: Authorization
      prefix: Bearer